# Generated by Django 3.2.4 on 2021-07-10 21:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210710_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='who_is',
            field=models.CharField(choices=[('P', 'Professor'), ('S', 'Student')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
