# Generated by Django 3.2.4 on 2021-07-10 21:40

from django.db import migrations
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_newuser_who_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='country',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=2),
            preserve_default=False,
        ),
    ]
