# Generated by Django 3.2.4 on 2021-07-12 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_who_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='zoom_url',
            field=models.URLField(default=''),
        ),
    ]
