# Generated by Django 3.2.4 on 2021-07-16 20:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_zoom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='field',
            field=models.CharField(choices=[('electronic', 'electronic'), ('computer', 'computer'), ('economic', 'economic')], default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
    ]
