# Generated by Django 3.2.4 on 2021-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_newuser_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='field',
            field=models.CharField(choices=[('electronic', 'electronic'), ('computer', 'computer'), ('economic', 'economic')], default='electronic', max_length=100),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='who_is',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Student', 'Student')], default='Student', max_length=10),
        ),
    ]
