# Generated by Django 3.2.4 on 2021-07-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
