# Generated by Django 3.2.4 on 2021-07-13 08:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_alter_meetings_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
