# Generated by Django 3.2.4 on 2021-07-14 11:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_auto_20210713_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='topic',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
