# Generated by Django 3.2.4 on 2021-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meetings_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetings',
            name='field',
            field=models.CharField(choices=[('electronic', 'electronic'), ('computer', 'computer'), ('economic', 'economic')], default='choose your field', max_length=100),
        ),
    ]
