# Generated by Django 3.2.4 on 2021-08-23 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meetings_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetings',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
