# Generated by Django 3.2.6 on 2021-08-24 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0008_meetings_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meetings',
            name='date_time',
        ),
    ]
